language: bash
sudo: required
env:
  global:
  - TRAVIS_CI_OPERATOR=1
  - secure: "YW2gcI38ofz9QxlQSMWh/X7xXnq1IvgL+edKQNWHh5lyBRA1eMJpGpQfozwDMwnE1pVHmuVKeP/XDiHSFBznNmqYN4Rnm7R06bN9yaKeg+Q3gvz6IrR+DywUZ69NzPtGEM1KHYTv5qA09rgsKLWP3Yj+PikjJRTEOZygbMYNuEA="
  - secure: "kKbGT9Oa8cuEVkVpPXPuSw3Gy6zrRR45plNYrmzs3hCB6TTEY9DvQmhbMyv5kkxvVn7Z2/QKWGlnTOs2wCIFizUJg8AMA6CaVmeP4eFl9/w2KUybVSBfctIjgD7MwZU/iRgVzhKMIQDxEx4vh3r8je8mM8aEkG6m+jLhPO46HQU="
services:
- docker
install:
- curl -L https://raw.githubusercontent.com/OriHoch/travis-ci-operator/master/travis_ci_operator.sh > $HOME/bin/travis_ci_operator.sh
- bash $HOME/bin/travis_ci_operator.sh init
- travis_ci_operator.sh docker-login
script:
- docker build -t uumpa/hasadna-ckan:latest -t uumpa/hasadna-ckan:${TRAVIS_COMMIT} . &&\
  docker push uumpa/hasadna-ckan:latest &&\
  docker push uumpa/hasadna-ckan:${TRAVIS_COMMIT}
